[project]
name = "bytewaves"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "reedsolo>=1.7.0",
    "sounddevice>=0.5.2",
]
